# Generated by Django 5.1.4 on 2026-07-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='sender_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='smtp_password_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='profile',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='welcome_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='welcome_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
