# Generated by Django 5.1.4 on 2026-08-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_sender_email_profile_sender_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='welcome_message_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='welcome_subject_en',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
