# Generated by Django 5.1.4 on 2026-08-27 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_reset_default_welcome_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='welcome_message_en',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='welcome_subject_en',
        ),
        migrations.CreateModel(
            name='WelcomeLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_ar', models.CharField(blank=True, max_length=255)),
                ('body_ar', models.TextField(blank=True)),
                ('subject_en', models.CharField(blank=True, max_length=255)),
                ('body_en', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
