# Generated by Django 5.1.4 on 2026-07-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_bilingual_and_investment_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='businesscard',
            new_name='cards_busin_company_120b35_idx',
            old_name='cards_busin_company_6ae40c_idx',
        ),
        migrations.RenameIndex(
            model_name='businesscard',
            new_name='cards_busin_created_a647b0_idx',
            old_name='cards_busin_created_a78cf4_idx',
        ),
    ]
