# Generated by Django 5.1.4 on 2026-07-29 08:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_card_owner_seq_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDomainEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_description', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('services', models.JSONField(blank=True, default=list)),
                ('products', models.JSONField(blank=True, default=list)),
                ('countries', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('raw_extracted_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('not_requested', 'لم يُطلب'), ('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('unavailable', 'غير متاح')], db_index=True, default='pending', max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('schema_version', models.CharField(blank=True, max_length=32)),
                ('content_hash', models.CharField(blank=True, max_length=128)),
                ('last_error', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_after', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='businesscard',
            name='review_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ExtractionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('image_fingerprint', models.CharField(blank=True, db_index=True, max_length=128)),
                ('schema_version', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل')], db_index=True, default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_requests', to='cards.businesscard')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraction_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeminiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('operation_type', models.CharField(choices=[('card_extraction', 'استخراج بطاقة'), ('website_enrichment', 'إثراء من الموقع')], db_index=True, default='card_extraction', max_length=32)),
                ('request_status', models.CharField(db_index=True, default='completed', max_length=20)),
                ('input_token_count', models.IntegerField(default=0)),
                ('output_token_count', models.IntegerField(default=0)),
                ('thoughts_token_count', models.IntegerField(blank=True, null=True)),
                ('cached_token_count', models.IntegerField(blank=True, null=True)),
                ('total_token_count', models.IntegerField(default=0)),
                ('request_count', models.IntegerField(default=1)),
                ('retry_number', models.IntegerField(default=0)),
                ('estimated_input_cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('estimated_output_cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('estimated_total_cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('cost_note', models.CharField(blank=True, max_length=120)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_type', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemini_usage_logs', to='cards.businesscard')),
                ('extraction_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='cards.extractionrequest')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemini_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='extractionrequest',
            index=models.Index(fields=['owner', 'image_fingerprint'], name='extreq_owner_fp_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractionrequest',
            constraint=models.UniqueConstraint(fields=('owner', 'idempotency_key'), name='uniq_owner_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='geminiusagelog',
            index=models.Index(fields=['operation_type', 'created_at'], name='usage_op_created_idx'),
        ),
    ]
