# Generated by Django 5.1.4 on 2026-07-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_companydomainenrichment_businesscard_review_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='welcome_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='welcome_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='welcome_sent_to',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='welcome_status',
            field=models.CharField(choices=[('not_sent', 'لم تُرسل'), ('sent', 'تم الإرسال'), ('failed', 'فشل الإرسال')], db_index=True, default='not_sent', max_length=20),
        ),
    ]
