# Generated by Django 5.1.4 on 2026-08-27 08:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_businesscard_welcome_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='printed_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='salutation_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='salutation_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='salutation_native',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='WelcomeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=16)),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('language', 'source_hash'), name='uniq_welcome_translation')],
            },
        ),
    ]
