# Generated by Django 5.1.4 on 2026-09-13 09:02

from django.db import migrations, models
from django.db.models import Max


def seed_counter(apps, schema_editor):
    """Start the counter at the highest number already issued.

    Without this the first card saved after the migration would be handed
    number 1 and collide with the existing rows.
    """
    BusinessCard = apps.get_model('cards', 'BusinessCard')
    CardNumberCounter = apps.get_model('cards', 'CardNumberCounter')
    highest = BusinessCard.objects.aggregate(peak=Max('sequence_number'))['peak'] or 0
    CardNumberCounter.objects.update_or_create(pk=1, defaults={'last_value': highest})


def drop_counter(apps, schema_editor):
    apps.get_model('cards', 'CardNumberCounter').objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_businesscard_printed_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardNumberCounter',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RunPython(seed_counter, drop_counter),
    ]
